Дз по модулю 8.
angelinagnedina/AAA-academy pull request #9
Opened 2022-12-02 18:44 UTC by angelinagnedina

2023-01-24 10:28 UTC, burmisha requested changes
Нужно немного почистить код. 
Было бы здорово в 3–4 задаче удастся заиспользовать часть кода из 1–2.

2023-01-24 10:28 UTC, burmisha commented on Algorithms_class/min_path_from_analytics_to_algorithm.py
> +        for line in f.readlines()[1:]:
так лучше не писать: оно вычитает весь файл в память, а потом начнёт обрабатывать.
```
for index, line in enumerate(f):
    if index == 0:
        continue
    ...
```

2023-01-24 10:28 UTC, burmisha commented on Algorithms_class/min_path_from_analytics_to_algorithm.py
> +            page_id, page_title = line.rstrip().split(',')[1:3]
Тут лучше использовать библиотеку для чтения csv: https://docs.python.org/3/library/csv.html#csv.DictReader

2023-01-24 10:28 UTC, burmisha commented on Algorithms_class/min_path_from_analytics_to_algorithm.py
> +    assert id_algorithm and id_analytics, 'No such pages'
Такой assert некорректен. Вдруг в нашем графе по стечению обстоятельств, например, `id_analytics == 0`. Тогда всё будет корректно, но assert скажет обратное.
Можно написать `assert (id_algorithm is not None) and (id_analytics  is not None)` (скобки лишь для читаемости). Но и тут: assert-ами не надо пользоваться в проде: https://docs.python.org/3/reference/simple_stmts.html#the-assert-statement

2023-01-24 10:28 UTC, burmisha commented on Algorithms_class/min_path_from_analytics_to_algorithm.py
> +    with open(filename2) as f:
Лучше будет вынести чтение файлов в отдельные функции.

2023-01-24 10:28 UTC, burmisha commented on Algorithms_class/min_weighted_path_from_analytics_to_algorithm.py
> +    open = [(0, start_node, start_node)]
Не стоит создавать переменные, совпадающие с ключевыми словами языка (даже если язык это позволяет).

2023-01-24 10:28 UTC, burmisha commented on Algorithms_class/min_weighted_path_from_analytics_to_algorithm.py
> +                graph[page_from] = [(len(page_names[page_to]), page_to)]
Была бы полезна структура «взвешенное ребро».

2023-01-30 17:07 UTC, angelinagnedina commented on Algorithms_class/min_weighted_path_from_analytics_to_algorithm.py
> +                graph[page_from] = [(len(page_names[page_to]), page_to)]
Привет, а можно ссылку, что за структура? Само понятие знакомо, но чтобы структура данных с таким названием - не слышала.

2023-02-01 10:05 UTC, burmisha commented on Algorithms_class/min_weighted_path_from_analytics_to_algorithm.py
> +                graph[page_from] = [(len(page_names[page_to]), page_to)]
Неоднозначно выразился, да. Не структура данных, а какой-нибудь класс. В простейшем случае хотя бы namedtuple:
`WeighedEdge = collections.namedtuple('WeighedEdge', 'start finish weight')`

2023-02-08 20:56 UTC, merged